### ISSUE TITLE
scorer.py AttributeError

### ISSUE THREAD

**Issue by bsimmons-onboard** [google/digitalbuildings#1004]
**Describe the bug**
Unable to run scorer.py, throws an AttributeError:

**To Reproduce**
`python3 tools/scoring/scorer.py -prop ahu_prop.yaml -sol ahu_solution.yaml`
...
`Scoring — building universe
FieldUniverse undefined in ConfigUniverse`
...
`Traceback (most recent call last):
  File "/home/brian/github/digitalbuildings/tools/scoring/scorer.py", line 72, in <module>
    pp.pprint(scorer.execute())
  File "/home/brian/github/digitalbuildings/tools/scoring/score/parse_config.py", line 248, in execute
    self.results = self.aggregate_results(
  File "/home/brian/github/digitalbuildings/tools/scoring/score/parse_config.py", line 218, in aggregate_results
    evaluated = dimension(deserialized_files=deserialized_files).evaluate()
  File "/home/brian/github/digitalbuildings/tools/scoring/score/dimensions/entity_point_identification.py", line 195, in evaluate
    self._evaluate_virtual(proposed_file=proposed_file,
  File "/home/brian/github/digitalbuildings/tools/scoring/score/dimensions/entity_point_identification.py", line 107, in _evaluate_virtual
    proposed_points_virtual = self._fetch_points_virtual(
  File "/home/brian/github/digitalbuildings/tools/scoring/score/dimensions/entity_point_identification.py", line 55, in _fetch_points_virtual
    return [
  File "/home/brian/github/digitalbuildings/tools/scoring/score/dimensions/entity_point_identification.py", line 57, in <listcomp>
    set(file[link.source].translation[target_field].raw_field_name
  File "/home/brian/github/digitalbuildings/tools/scoring/score/dimensions/entity_point_identification.py", line 57, in <genexpr>
    set(file[link.source].translation[target_field].raw_field_name
AttributeError: 'UndefinedField' object has no attribute 'raw_field_name'`

**OS (please complete the following information):**
Ubuntu 

**Test Files**
Sending test files to digitalbuildings-support@googlegroups.com

**Comment by bsimmons-onboard** [comment]
Looks like this is caused by MISSING fields. I was able to run the scoring tool after removing them from the prop and solution files.

**Comment by charbull** [comment]
@mschulze17 @trav3711 we need to update the scorer to support the missing fields, it could be a P2 but would be worth it to capture it somewhere internally

**Comment by trav3711** [comment]
@bsimmons-onboard Is this issue blocking for you?

**Comment by bsimmons-onboard** [comment]
@trav3711 I can proceed with a workaround where I remove missing fields from the prop and solution files. From the README it seems like missing types are intended to factor into the score.
https://github.com/google/digitalbuildings/tree/master/tools/scoring#caveats

**Comment by charbull** [comment]
@bsimmons-onboard assigned this bug to you :)

**Comment by charbull** [comment]
Chatted and reassigning to @trav3711
