### ISSUE TITLE
Instance Validator - Bugging out

### ISSUE THREAD

**Issue by oli-barker** [google/digitalbuildings#268]
**Describe the bug**
When i run instance validator against an building_config.yaml file I now get the following error output error:

oli@zerocool:~/temporary/digitalbuildings/tools/validators/instance_validator$ python3 instance_validator.py -i /media/sf_shared/Building_Config_Test.yaml
Starting validator...
Starting universe generation...
Starting config validation...
Loading config files...
Validating syntax please wait ...
Opening file: /media/sf_shared/Building_Config_Test.yaml, please wait ...
Starting config validation...
Validating entities ...
Traceback (most recent call last):
  File "instance_validator.py", line 104, in <module>
    handler.RunValidation(args.filenames, args.modified_types_filepath,
  File "/home/oli/temporary/digitalbuildings/tools/validators/instance_validator/validate/handler.py", line 96, in RunValidation
    entities = _ValidateConfig(filenames, universe)
  File "/home/oli/temporary/digitalbuildings/tools/validators/instance_validator/validate/handler.py", line 67, in _ValidateConfig
    return helper.Validate(entities, config_mode)
  File "/home/oli/temporary/digitalbuildings/tools/validators/instance_validator/validate/handler.py", line 224, in Validate
    if not validator.Validate(current_entity):
  File "/home/oli/temporary/digitalbuildings/tools/validators/instance_validator/validate/entity_instance.py", line 84, in Validate
    return iv.Validate(entity) and gv.Validate(entity)
  File "/home/oli/temporary/digitalbuildings/tools/validators/instance_validator/validate/entity_instance.py", line 433, in Validate
    if not self._ConnectionsAreValid(entity):
  File "/home/oli/temporary/digitalbuildings/tools/validators/instance_validator/validate/entity_instance.py", line 305, in _ConnectionsAreValid
    if not (self.universe.connection_universe and entity.connections):
AttributeError: 'ConfigUniverse' object has no attribute 'connection_universe'

I have tried this with both my custom building_config and also the suggested demo version from fake_instances/GOOD/good_building_connections.yaml

When I tested against a previous version of the DBO the file validated.

**To Reproduce**

python3 instance_validator.py -i "path to building instance"

**Expected behavior**

I expected the validator to either validate or report on what was not configured correctly within my building_config.yaml

**Comment by charbull** [comment]
Can you please run the following:

python3 setup.py install

 

First in digitalbuildings/tools/validators/ontology_validator

then in the instance validator
