### ISSUE TITLE
Invalid JSON causes instance validator to crash

### ISSUE THREAD

**Issue by noursaidi** [google/digitalbuildings#724]
**Describe the bug**
When processing a message a message which is invalid JSON, e.g. extra comma, use of single quotes instead of double quotes, the instance validator crashes out with an invalid message exception.

**To Reproduce**
Validate a subscription which is receiving invalid JSON messages

**Expected behavior**
The entity is marked as a failure for invalid message

**Screenshots**
```
Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 117, in _wrap_callback_errors
    callback(message)
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validator.py", line 119, in ValidateMessage
    tele = telemetry.Telemetry(message)
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry.py", line 46, in __init__
    self._parse_data(message.data))
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry.py", line 83, in _parse_data
    json_object = json.loads(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 15712 (char 15711)
Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 117, in _wrap_callback_errors
    callback(message)
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validator.py", line 119, in ValidateMessage
    tele = telemetry.Telemetry(message)
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry.py", line 46, in __init__
    self._parse_data(message.data))
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry.py", line 83, in _parse_data
    json_object = json.loads(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 15712 (char 15711)
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py:577: RuntimeWarning: Scheduling a callback after executor shutdown.
  self._scheduler.schedule(self._callback, msg)
```

**OS (please complete the following information):**
mac

**Comment by noursaidi** [comment]
Also encountered a similar issue processing a message which seemed to have a payload which was just - `1` (the number 1)

```
Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 117, in _wrap_callback_errors
    callback(message)
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validator.py", line 119, in ValidateMessage
    tele = telemetry.Telemetry(message)
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry.py", line 46, in __init__
    self._parse_data(message.data))
  File "/Users/nournew/digitalbuildings/tools/validators/instance_validator/validate/telemetry.py", line 84, in _parse_data
    version = json_object.get(VERSION,1) # If the verison is missing, assume v1
AttributeError: 'int' object has no attribute 'get'
```

**Comment by charbull** [comment]
@trav3711 @mschulze17 can we please take a look at this in the current sprint. It is a P1 bug.

**Comment by trav3711** [comment]
Fixed internally and will be migrated to Github within a week.
