### ISSUE TITLE
telemetry validation stops. error message is: 'MultiStateValue' object has no attribute 'point_name' but no specific info to find it easily on the pointlist

### ISSUE THREAD

**Issue by josephedwardchang** [google/digitalbuildings#916]
**IMPORTANT**
DO NOT INCLUDE ANY PROJECT-SPECIFIC INFORMATION IN THIS TICKET!
ANY PROJECT-SPECIFIC CONTEXT (E.G. BUILDING CONFIG INPUTS) SHOULD BE
EMAILED DIRECTLY TO: digitalbuildings-support@googlegroups.com

PLEASE REFERENCE THIS ISSUE LINK IN YOUR EMAIL TO THAT GROUP

**Description**

Hi All,
I am doing the telemetry validation with pubsub access. I'm having trouble pinpointing the exact pointlist item or DDC where the error below is encountered. I understand the error: 'MultiStateValue' object has no attribute 'point_name' to mean that there is a malformed json that a pointlist item (a multistate: ON/OFF, CLOSED/OPEN, RUN/STOP, etc) doesn't have a "present_value" accompanying it. But it doesn't help that it doesn't show the exact pointlist name or the DDC that has the error.

I have validated this with the UDMI validator (with pubsub validation) and there is no mention of any missing present_value. 

short of turning off all the DDCs in registry (make them disabled) and running telemetry validation for each one (DDC), is there a better way to identify the message (or pointlist or DDC) where the error occurs? 

```
[INFO]  Starting validation process.
/home/test/env/lib/python3.8/site-packages/google/auth/_default.py:81: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/home/test/env/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 126, in _wrap_callback_errors
    callback(message)
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validator.py", line 232, in ValidateMessage
    self.CallbackIfCompleted()
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validator.py", line 142, in CallbackIfCompleted
    self.callback(self)
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/handler.py", line 258, in _TelemetryValidationCallback
    validation_report_dict = validation_report.GenerateReport()
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validation_report.py", line 110, in GenerateReport
    ERROR_DEVICES: [
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validation_report.py", line 111, in <listcomp>
    block.CreateJsonReportBlock() for block in self.error_devices
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validation_report.py", line 195, in CreateJsonReportBlock
    EXPECTED_POINTS: self._TelemetryPointListToDict(self.expected_points),
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validation_report.py", line 233, in _TelemetryPointListToDict
    point_dictionary = {
  File "/home/test/digitalbuildings/tools/validators/instance_validator/validate/telemetry_validation_report.py", line 234, in <dictcomp>
    point.point_name: {PRESENT_VALUE_KEY: point.present_value}

----
AttributeError: 'MultiStateValue' object has no attribute 'point_name'
----

[INFO]  Instance validation report generated: <_io.TextIOWrapper name='/home/test/dbo_report.txt' mode='w' encoding='utf-8'>
[INFO]  Instance validation completed.
```

**Steps To Reproduce**
1. Have a DDC send a malformed json pointset with an item there missing a present_value
2. run DBO telemetry validation for that DDC (i used the ALL-In-ONE instance validator) 
3. See description above for the error message
4. When validation is run again, sometimes the error would be: AttributeError: 'DimensionalValue' object has no attribute 'point_name'. I suppose this means the pointlist is expecting decimal value but that there is no "present_value"?

**Expected behavior**
There should be some info on the error which shows at least the pointname, say, "dehumidifer_status_12", so that it would be easier to look it up on our DDC and pointslist and make corrections. I guess this may not be a priority as it is not actually a bug but a "nice to have" feature

**Screenshots**
none

**OS:**
Linux Ubuntu 20.04.05 LTS running on WSL 1.0 on Windows 10 x64

**Additional context**
DBO instance validator or telemetry validator

**Comment by josephedwardchang** [comment]
oh. thank you sir
